#!/bin/bash

# starts Scream with IVSHMEM
/usr/bin/scream -i virbr0

# wait for any of the processes to exit. (Like closing the Looking Glass window)
wait -n

# kill the remaining processes (Like scream)
pkill -P $$
